### PR TITLE
Fix disabled zones

### LINKED ISSUE #35: Error in climate entity during startup
it worked earlier today - but after some restarts of home-assistant I do only get those messages and the climate entity is gone:

```
2020-07-01 23:51:48 ERROR (MainThread) [homeassistant.components.climate] Error while setting up vaillant platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 443, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 173, in state
    return self.hvac_mode
  File "/config/custom_components/vaillant/climate.py", line 155, in hvac_mode
    hvac_mode = self.mode_to_hvac(self.active_mode.current)
  File "/config/custom_components/vaillant/climate.py", line 347, in active_mode
    return self._system.get_active_mode_zone(self.component)
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/model/system.py", line 133, in get_active_mode_zone
    mode: ActiveMode = zone.active_mode
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/model/zone.py", line 72, in active_mode
    return self.heating.active_mode
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/model/common.py", line 52, in active_mode
    setting = self.time_program.get_for(datetime.now())
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/model/timeprogram.py", line 107, in get_for
    tp_day = self.days[day]
KeyError: 'wednesday'
```

### PR DESCRIPTION
**Pull request by h4de5**
Fixes #35

### CODE REVIEW

**Comment by thomasgermain** [comment]
Hi,

thanks for the PR. This one is a bit special, because this is the first one done by somebody else then me :smiley: 

In order to make the PR build, the doc has to be updated, It can be done by calling make inside the `doc` folder. (You will need to activate the venv).

**Comment by h4de5** [comment]
ok. tests seem to be ok:

```
python3.8 -m unittest
......................................................................................................................
----------------------------------------------------------------------
Ran 118 tests in 0.090s

OK
```

the docs update seems to be pretty big.

**Comment by h4de5** [comment]
mmh. `./html-diff.sh` does not give me any output after make.

**Comment by h4de5** [comment]
ok. if github goes down, then because of me refreshing on that status page...

2 of 3 successfull tests ..

**Comment by thomasgermain** [comment]
Actually, you have to run `make html` in order to generate html. I also had to remember how to regenerate the doc :disappointed_relieved:

**Comment by h4de5** [comment]
`make html` removed now one of the jquery files - but left the html untouched. I hope thats ok?

**Comment by h4de5** [comment]
is it possible, that the last check is your approval?

**Comment by thomasgermain** [comment]
Yes I have to approve it :yum: 

I was expecting the `Travis CI - Branch` to run, but I guess it won't because this is a fork

**Comment by h4de5** [comment]
actually I was about to copy that CI part for my own HA integration - so no worries.

btw: I could use some (a lot of) help with config_flow, reproduce_state and some other HA related stuff - so..as soon as sort out that odds and ends here, feel free to drop by 😁 

https://community.home-assistant.io/t/vimar-integration-wip/202073

regarding the squash: a new PR?

**Comment by thomasgermain** [comment]
Oh yeah, I didn't realize I could do it myself :disappointed_relieved: I'm used to do it via command line :)

Anyway, Thanks for your contribution, I'm gonna merge it and release it.

Feel free to ping me if you need some help for config flow :)

**Pull request merged**
